# Version: 2024.06.1
# Asuswrt Package
# For this to work asuswrt integration needs to be setup.


script:
  # Script to update this package from GitHub
  update_packages:
    sequence:
      - service: downloader.download_file
        data:
          overwrite: true
          url: >-
            {% set url = 'https://raw.githubusercontent.com/' %}
            {% if states.input_text.packages_account.state is defined %}
              {% set account = states('input_text.packages_account') %}
            {% else %}
              {% set account = 'topaniot' %}
            {% endif %}
            {% set path = '/HomeAssistant_Packages/main/packages/' %}
            {% set name = 'asuswrt.yaml' %}
            {{ url + account + path + name }}


automation:
# Notify when CPU Temperature is high
  - id: 'asuswrt_cpu_temp'
    alias: " Asuswrt CPU Temperature"
    description: ''
    trigger:
      - platform: numeric_state
        entity_id: sensor.asuswrt_cpu_temperature
        above: '80'
    condition: []
    action:
      - service: >-
          {% if states.input_text.notify_service_server.state is defined %}
            {% set notify_service = states('input_text.notify_service_server') %}
          {% elif states.input_text.notify_service.state is defined %}
            {% set notify_service = states('input_text.notify_service') %}
          {% else %}
            {% set notify_service = 'notify' %}
          {% endif %}
          {{ "notify." + notify_service }}
        data:
          message: "🟡 Asuswrt CPU Temp. = {{ states('sensor.asuswrt_cpu_temperature') }}°C"
      - wait_template: "{{ states( 'sensor.asuswrt_cpu_temperature' ) | float < 75 }}"
      - service: >-
          {% if states.input_text.notify_service_server.state is defined %}
            {% set notify_service = states('input_text.notify_service_server') %}
          {% elif states.input_text.notify_service.state is defined %}
            {% set notify_service = states('input_text.notify_service') %}
          {% else %}
            {% set notify_service = 'notify' %}
          {% endif %}
          {{ "notify." + notify_service }}
        data:
          message: "🟢 Asuswrt CPU Temp. = {{ states('sensor.asuswrt_cpu_temperature') }}°C"
    mode: single
    max_exceeded: silent

# Notify when 2.4GHz Temperature is high
  - id: 'asuswrt_24ghz_temp'
    alias: " Asuswrt 2.4GHz Temperature"
    description: ''
    trigger:
      - platform: numeric_state
        entity_id: sensor.asuswrt_2_4ghz_temperature
        above: '60'
    condition: []
    action:
      - service: >-
          {% if states.input_text.notify_service_server.state is defined %}
            {% set notify_service = states('input_text.notify_service_server') %}
          {% elif states.input_text.notify_service.state is defined %}
            {% set notify_service = states('input_text.notify_service') %}
          {% else %}
            {% set notify_service = 'notify' %}
          {% endif %}
          {{ "notify." + notify_service }}
        data:
          message: "🟡 Asuswrt 2.4GHz Temp. = {{ states('sensor.asuswrt_2_4ghz_temperature') }}°C"
      - wait_template: "{{ states( 'sensor.asuswrt_2_4ghz_temperature' ) | float < 55 }}"
      - service: >-
          {% if states.input_text.notify_service_server.state is defined %}
            {% set notify_service = states('input_text.notify_service_server') %}
          {% elif states.input_text.notify_service.state is defined %}
            {% set notify_service = states('input_text.notify_service') %}
          {% else %}
            {% set notify_service = 'notify' %}
          {% endif %}
          {{ "notify." + notify_service }}
        data:
          message: "🟢 Asuswrt 2.4GHz Temp. = {{ states('sensor.asuswrt_2_4ghz_temperature') }}°C"
    mode: single
    max_exceeded: silent

# Notify when 5GHz Temperature is high
  - id: 'asuswrt_5ghz_temp'
    alias: " Asuswrt 5GHz Temperature"
    description: ''
    trigger:
      - platform: numeric_state
        entity_id: sensor.asuswrt_5ghz_temperature
        above: '60'
    condition: []
    action:
      - service: >-
          {% if states.input_text.notify_service_server.state is defined %}
            {% set notify_service = states('input_text.notify_service_server') %}
          {% elif states.input_text.notify_service.state is defined %}
            {% set notify_service = states('input_text.notify_service') %}
          {% else %}
            {% set notify_service = 'notify' %}
          {% endif %}
          {{ "notify." + notify_service }}
        data:
          message: "🟡 Asuswrt 5GHz Temp. = {{ states('sensor.asuswrt_5ghz_temperature') }}°C"
      - wait_template: "{{ states( 'sensor.asuswrt_5ghz_temperature' ) | float < 55 }}"
      - service: >-
          {% if states.input_text.notify_service_server.state is defined %}
            {% set notify_service = states('input_text.notify_service_server') %}
          {% elif states.input_text.notify_service.state is defined %}
            {% set notify_service = states('input_text.notify_service') %}
          {% else %}
            {% set notify_service = 'notify' %}
          {% endif %}
          {{ "notify." + notify_service }}
        data:
          message: "🟢 Asuswrt 2.4GHz Temp. = {{ states('sensor.asuswrt_5ghz_temperature') }}°C"
    mode: single
    max_exceeded: silent
