# Version 2025.3.1
# NginX restart once per week

automation:
    # Restart NginX addon weekly
  - id: restart_nginx_addon
    alias: "𐃏 Restart NginX Addon"
    description: ""
    triggers:
      - trigger: time
        at: "05:00:00"
    condition:
      - condition: time
        weekday:
          - fri
    actions:
      - if:
          - condition: template
            value_template: >-
              {{ states('update.nginx_home_assistant_ssl_proxy_update') is defined }}
        then:
          - action: hassio.addon_restart
            data:
              addon: core_nginx_proxy
    mode: restart
